#!/usr/bin/env bash

NAME=$1

if [ $# -lt 1 ]; then
    echo "Usage: rgen <project-name>"
    exit 1
fi

cargo new "$NAME"

cat <<EOF > "$NAME"/Makefile
FEATURES="default"
NAME=$NAME

.PHONY: run
run:
	cargo run --features \$(FEATURES)

.PHONY: build
build:
	cargo build --features \$(FEATURES)

.PHONY: test
test:
	cargo test --features \$(FEATURES)

.PHONY: release
release:
	cargo build --release --features \$(FEATURES)

.PHONY: install
install:
	mv target/release/\$(NAME) /usr/bin/

.PHONY: publish
publish:
	cargo publish

.PHONY: fmt
fmt:
	rustfmt **/*.rs

.PHONY: lint
lint:
	cargo clippy
EOF

cat <<EOF > "$NAME"/.gitignore
target/
EOF
