#!/bin/bash

cd ~/repos/unity
tmux new-session -d -s work

# emacs
tmux rename-window editor

# terminal
tmux new-window -t work -n term
tmux split-window -h
tmux select-pane -t 1
tmux send-keys -t 1 "ai"

# kubernetes
tmux new-window -t work -n k9s
tmux send-keys -t work:2 'k9s' C-m

tmux attach-session -t work:0
